module.exports = [
  "Have a pawsome day! :3",
  "You got this, keep going!",
  "Small steps still move you forward.",
  "Progress beats perfection every time.",
  "You are allowed to take up space.",
  "Your best today is enough.",
  "Breathe. You are doing fine.",
  "One thing at a time.",
  "You have survived every hard day so far.",
  "Rest is productive too.",
  "You are more capable than you feel right now.",
  "Done is better than perfect.",
  "Your effort is not invisible.",
  "Today counts, even the quiet parts.",
  "You are learning, and that is the point.",
  "Be as kind to yourself as you are to others.",
  "The hard part will pass.",
  "You do not have to earn your worth.",
  "Keep the promise you made to yourself.",
  "Slow progress is still progress.",
  "You are exactly where you need to start.",
  "Your pace is the right pace.",
  "Mistakes mean you are trying.",
  "You can begin again at any moment.",
  "Courage is just showing up.",
  "Your future self is cheering for you.",
  "Let it be messy and do it anyway.",
  "You are not behind, you are on your own timeline.",
  "Ask for help. That is strength.",
  "You have handled harder than this.",
  "Trust the work you are putting in.",
  "Today does not have to be perfect to be good.",
  "You are allowed to change your mind.",
  "Momentum starts with one small move.",
  "Your ideas are worth sharing.",
  "You belong in the room.",
  "It is okay to go slowly.",
  "You are becoming who you want to be.",
  "Focus on the next right thing.",
  "You are stronger than the doubt.",
  "Something good is on its way.",
  "You are worthy of good things.",
  "Give yourself credit today.",
  "Your feelings are valid.",
  "You can do hard things.",
  "Softness is not weakness.",
  "One deep breath changes everything.",
  "You are doing better than you think.",
  "Let today be simple.",
  "You are allowed to rest without guilt.",
  "The effort matters even when the result is delayed.",
  "You are not alone in this.",
  "Keep going, quietly and steadily.",
  "Your curiosity will carry you far.",
  "You make things better by being here.",
  "Choose progress over pressure.",
  "It is okay to start over.",
  "You are enough as you are.",
  "The small wins add up.",
  "Be proud of how far you have come.",
  "You are allowed to be a work in progress.",
  "Your patience will pay off.",
  "Today is a fresh page.",
  "You handle uncertainty better than you know.",
  "You are resilient by practice, not by luck.",
  "Let go of what you cannot control.",
  "Your voice matters.",
  "You can be tired and still be strong.",
  "One task, then another.",
  "You are worth the effort you give others.",
  "Kindness to yourself compounds.",
  "You are not your worst day.",
  "Show up, that is the whole trick.",
  "There is time for this.",
  "You are building something real.",
  "Give it a try before you judge it.",
  "The next version of you starts now.",
  "You are doing meaningful work.",
  "Consistency beats intensity.",
  "Your growth is not always visible yet.",
  "It is safe to slow down.",
  "You deserve a break you do not have to earn.",
  "Confidence comes after action, not before.",
  "You are figuring it out.",
  "Everything you need is already in motion.",
  "You have permission to keep it simple.",
  "Your attention is valuable, spend it well.",
  "You are allowed to be proud.",
  "Steady hands, steady heart.",
  "You do not need to rush your healing.",
  "Little by little becomes a lot.",
  "You are capable of change.",
  "Today you get to try again.",
  "Your presence is a gift.",
  "You are not too much.",
  "You are not too late.",
  "Difficulty is not a sign to quit.",
  "You can hold hope and doubt at once.",
  "Take the next small step.",
  "You are worth rooting for.",
  "Let yourself be a beginner.",
  "Your standards can bend today.",
  "You are more than your output.",
  "Good enough is genuinely good.",
  "You are handling it.",
  "Be gentle with your mind today.",
  "You do not have to do it all at once.",
  "Your work has value beyond the metrics.",
  "Look how far you have already come.",
  "The path clears as you walk it.",
  "You have good instincts, trust them.",
  "Say yes to the thing that scares you a little.",
  "You are learning something every single day.",
  "Rest, then rise.",
  "Your calm is a superpower.",
  "You can only start from where you are.",
  "You are allowed to protect your energy.",
  "Progress is rarely a straight line.",
  "Today is a good day to be kind to you.",
  "You are doing something brave right now.",
  "Your persistence is remarkable.",
  "Keep your standards, drop the shame.",
  "You are the expert on your own life.",
  "One honest attempt is enough.",
  "There is room for you to grow.",
  "You are allowed to want more.",
  "Slow down, you are not late.",
  "You bring something no one else does.",
  "Your ideas deserve daylight.",
  "It is okay to not know yet.",
  "You are stronger after every setback.",
  "Let curiosity lead today.",
  "Your best is variable and that is fine.",
  "You are worthy of patience.",
  "Nothing is wasted, it is all practice.",
  "You can rebuild anything.",
  "This moment is workable.",
  "You are doing your part.",
  "Choose the easier next step.",
  "You are allowed to celebrate small things.",
  "Your body is doing its best for you.",
  "Take up the space you need.",
  "You are not behind anyone.",
  "The work will meet you halfway.",
  "You have already proven you can adapt.",
  "Give the day a chance.",
  "Your kindness ripples further than you see.",
  "Keep the faith in your own effort.",
  "You are enough for today.",
  "Focus is a muscle, not a mood.",
  "Just begin, badly if needed.",
  "You are steadier than you feel.",
  "Let this be easier than you expect.",
  "You are worth the time it takes.",
  "You can put it down and come back.",
  "Your progress is real even when quiet.",
  "The next hour can be different.",
  "You are allowed to be human here.",
  "Do the small thing, then decide.",
  "Your future is being built right now.",
  "You are capable of surprising yourself.",
  "One kind thought changes the tone.",
  "You can be scared and go anyway.",
  "You are welcome exactly as you are.",
  "There is no rush on this.",
  "You are worth the care you give.",
  "Keep it light, keep it moving.",
  "You have every right to try.",
  "Your questions are good questions.",
  "You are not failing, you are iterating.",
  "The pressure is optional.",
  "You are permitted to be pleased with yourself.",
  "Small effort, repeated, wins.",
  "You are safe to try something new.",
  "Let today be enough.",
  "You are on the right track.",
  "Your consistency is impressive.",
  "It is fine to change direction.",
  "You are learning faster than you notice.",
  "Give yourself an easier target.",
  "You can always adjust the plan.",
  "You are not required to be impressive.",
  "Your presence steadies people.",
  "This will make sense later.",
  "You have room to breathe.",
  "You are permitted to go at half speed.",
  "The work is worth doing imperfectly.",
  "You are more than halfway to something.",
  "Kindness first, output second.",
  "You are allowed to enjoy this.",
  "Keep choosing yourself.",
  "You are quietly doing great.",
  "Every day you show up is a win.",
  "You can figure out the next part later.",
  "Your instincts have served you well.",
  "You are allowed to say no.",
  "Take the pressure off and just start.",
  "You are exactly enough.",
  "The tough stretch is temporary.",
  "You are doing something worthwhile.",
  "Progress hides in ordinary days.",
  "You have permission to rest now.",
  "You are getting better at this.",
  "One thing done well is plenty.",
  "You are allowed to be excited.",
  "The next attempt will be smoother.",
  "You are learning to trust yourself.",
  "Keep it simple and keep going.",
  "You are worthy of a good day.",
  "Take heart, this is working.",
  "You do not owe anyone perfection.",
  "The details will come together.",
  "You are steady, even in the noise.",
  "Small kindness, big difference.",
  "You are doing the brave, boring work.",
  "There is still plenty of time.",
  "You have already come so far.",
  "Try it once, gently.",
  "You are allowed to be uncertain.",
  "Your calm effort is enough.",
  "You are shaping something good.",
  "It gets lighter from here.",
  "You are permitted to take the long way.",
  "Notice one good thing right now.",
  "You are capable and you are cared for.",
  "Let the next step be tiny.",
  "You are making it work.",
  "Nothing about you needs fixing today.",
  "Your pace is sustainable and that matters.",
  "You are allowed to be proud of small wins.",
  "Keep breathing, keep building.",
  "You are handling more than most realize.",
  "The finish line moves, that is normal.",
  "You are doing enough right now.",
  "Trust that effort accumulates.",
  "You are allowed to enjoy the process.",
  "This is a good place to pause.",
  "You are still becoming, and that is beautiful.",
  "Your work today will matter tomorrow.",
  "You can be proud without being finished.",
  "Take the win, however small.",
  "You are on your way.",
  "Let go of the timeline for a minute.",
  "You have a good head on your shoulders.",
  "You are allowed to try the easy way.",
  "The mess is part of making things.",
  "You are welcome to start small.",
  "Your patience with yourself is growing.",
  "Keep the streak alive, gently.",
  "You are doing better than yesterday.",
  "There is strength in your steadiness.",
  "You can hold this lightly.",
  "You are not the only one who struggles here.",
  "Give yourself the benefit of the doubt.",
  "You are moving in a good direction.",
  "One more try is always allowed.",
  "You are worth being patient with.",
  "The next idea is already coming.",
  "You are allowed to feel good about this.",
  "Steady effort, no drama.",
  "You have made it through every single day.",
  "Let it be simple today.",
  "You are quietly becoming excellent.",
  "Your care shows in the details.",
  "Take a moment, you have earned it.",
  "You are doing something few would attempt.",
  "The work is patient, so can you be.",
  "You are allowed to reset the day.",
  "Your energy is worth protecting.",
  "You are not stuck, you are pausing.",
  "Keep it up, seriously.",
  "You are a good thing in someone's day.",
  "This effort will compound.",
  "You are allowed to be tired and still proud.",
  "Nothing needs to be decided right now.",
  "You are doing the right kind of hard.",
  "Let yourself be encouraged.",
  "You are more consistent than you give credit for.",
  "The good stretch is coming.",
  "You are allowed to want a gentler day.",
  "One thing, then rest.",
  "You are capable of finishing this.",
  "Your standards are worth the effort.",
  "You are allowed to try again tomorrow.",
  "Keep going, you are closer than you think.",
  "Your attention to this matters.",
  "You can course correct at any point.",
  "You are being kinder to yourself lately.",
  "The work you do quietly still counts.",
  "You are allowed to take the credit.",
  "Small brave choices build a life.",
  "You are learning what works for you.",
  "Give yourself a moment of pride.",
  "You are not behind, just human.",
  "This is a good effort, full stop.",
  "You are allowed a slow start.",
  "Your resilience is quietly impressive.",
  "Keep at it, it is landing.",
  "You are doing this your own way.",
  "There is grace for today.",
  "You are permitted to feel hopeful.",
  "One good decision at a time.",
  "You are worth the investment.",
  "Let the next step be obvious and small.",
  "You are making steady progress.",
  "Your calm is contagious.",
  "You have handled surprises before.",
  "You are allowed to keep it low key.",
  "Today's effort is already enough.",
  "You are building good habits.",
  "The work will still be there after a break.",
  "You are doing it, right now.",
  "Be proud of the boring consistency.",
  "You are allowed to want ease.",
  "Your progress is yours to define.",
  "One more small push.",
  "You are noticed and appreciated.",
  "There is space for you to breathe here.",
  "You are doing something kind for future you.",
  "Keep your head up, it is going fine.",
  "You are allowed to trust yourself on this.",
  "Good work is often invisible work.",
  "You are showing up, and that is huge.",
  "The hard part is almost behind you.",
  "You are allowed to be gentle today.",
  "Your effort deserves acknowledgement.",
  "Take it one minute at a time.",
  "You are doing beautifully."
];
